---
- name: Update and upgrade APT packages
  hosts: all
  become: yes
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade installed packages
      ansible.builtin.apt:
        upgrade: yes

    - name: Autoremove unnecessary packages
      ansible.builtin.apt:
        autoremove: yes

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Notify if a reboot is required
      ansible.builtin.debug:
        msg: "A reboot is required on {{ inventory_hostname }}."
      when: reboot_required.stat.exists
