---
- name: Ensure UFW is installed, enabled, and configured
  hosts: all
  become: true
  tasks:
    - name: Install UFW
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: true

    - name: Enable UFW if not enabled
      ansible.builtin.shell: |
        set -o pipefail
        ufw status | grep -qw active || ufw --force enable
      args:
        executable: /bin/bash
      changed_when: false

    - name: Allow SSH on port 22
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Allow SSH on port 4488
      community.general.ufw:
        rule: allow
        port: 4488
        proto: tcp
