---
- name: Harden SSH configuration
  hosts: test_boxes
  become: true
  tasks:
    - name: Update /etc/ssh/sshd_config with hardened settings
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        backup: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK - SSH Hardening"
        block: |
          Port 4488
          Protocol 2
          PermitRootLogin no
          PasswordAuthentication no
          ChallengeResponseAuthentication no
          PubkeyAuthentication yes
          PermitEmptyPasswords no
          X11Forwarding no
          MaxAuthTries 3
          AllowAgentForwarding no
          AllowTcpForwarding no
          LogLevel VERBOSE
      notify: Restart SSH

    - name: Allow SSH on port 4488
      community.general.ufw:
        rule: allow
        port: 4488
        proto: tcp

    - name: Deny SSH on port 22
      community.general.ufw:
        rule: deny
        port: 22
        proto: tcp

    - name: Ensure SSH service is enabled and started
      ansible.builtin.systemd:
        name: ssh
        enabled: true
        state: started

  handlers:
    - name: Reload and Restart SSH
      block:
        - name: Reload systemd daemon
          ansible.builtin.systemd:
            daemon_reload: true
          become: true
        - name: Restart SSH
          ansible.builtin.service:
            name: ssh
            state: restarted
